### ISSUE TITLE
Containers with same hostname/domainname can't resolve eachother

### ISSUE THREAD

**Issue by Multiply** [weaveworks/weave#1970]
We're currently using Weave with custom domain names, for each new environment we start up, to namespace things properly, and containers with the same hostname, cannot resolve eachother, unless we query for DNS directly.

We use Swarm (not that I think it matters), Weave Proxy, and Compose.

To start containers, we define our Swarm as the docker host, which is sending traffic into the Weave Daemon, rather than the original Docker Daemon.

Our containers can't resolve other containers in general, if we don't either define the FQDN as the hostname, or use a combination of hostname, and domainname in our compose.yml-files.

Example that works for us:
```
foo:
  image: foo
  hostname: foo
  domainname: bar.weave.local
```

This container will have a `/etc/hosts` file with contents similar to:
```
# created by Weave - BEGIN
# container hostname
10.34.0.4    foo.bar.weave.local foo

# static names added with --add-host

# default localhost entries
127.0.0.1       localhost
::1             ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
# created by Weave - END
```

The problem here is that it's adding the FQDN, and not just the hostname, so it will never be able to resolve other containers with the same hostname.

I'd like to either choose not to use the FQDN in the hosts-file, or have some way to query for DNS records, with an added prefix, like `_foo.bar.weave.local` (not a good way to do it at all, but it's just to get the idea out there)

**Comment by rade** [comment]
Try `getent hosts.foo.weave.local.` - notice the trailing dot.

```
$ weave launch
$ eval $(weave env)
$ docker run --name=foo1 -h foo.weave.local -dti ubuntu
bb81dd3c887d717a0816f416ef42a24ce468e63d429ebd1f41e51729b351ee15
$ docker run --name=foo2 -h foo.weave.local -dti ubuntu
f766711fc7f23167eaf172e131d67643eacd8c30251a2334110a811950a9b87d
$ docker exec foo1 getent hosts foo
10.32.0.1       foo.weave.local foo
$ docker exec foo1 getent hosts foo.weave.local
10.32.0.1       foo.weave.local foo
$ docker exec foo1 getent hosts foo.weave.local.
10.32.0.1       foo.weave.local
10.32.0.2       foo.weave.local
```

This does depend on the resolver. Doesn't work in alpine, the benchmark for broken DNS resolvers.

**Comment by rade** [comment]
We should probably document this behaviour.

**Comment by abuehrle** [comment]
I'll add a topic for this one.

**Comment by Multiply** [comment]
It might be related to this issue, maybe: https://github.com/docker/docker/issues/14282

**Comment by bboreham** [comment]
@multiply it is the same area, but that issue is focused on the hostname being configured incorrectly while this issue is about the FQDN being resolved via /etc/hosts.  The latter is not incorrect, but it does produce inconsistent behaviour.

**Comment by rade** [comment]
@Multiply have you given my "add a trailing dot" suggestion a try?

**Comment by Multiply** [comment]
@rade I did, yes. Eventually, we stopped using custom domains, because it wasn't exactly needed in the long run.

**Comment by Multiply** [comment]
To clarify: It still won't see other containers, even with the trailing dot on the end.

**Comment by rade** [comment]
> To clarify: It still won't see other containers, even with the trailing dot on the end.

Please provide the *exact* steps to reproduce this.

**Comment by rade** [comment]
> Doesn't work in alpine

```
/ # getent hosts foo
10.40.0.0         foo.weave.local  foo.weave.local foo
/ # getent hosts foo.weave.local.
10.32.0.1         foo.weave.local.  foo.weave.local.
```

Notice how the answer changes but only returns one result. Repeated queries return a different result, so I think it's just picking the first answer from the result set. This problem is not specific to looking up the container's own name; the same behaviour arises when looking up other names that have multiple DNS entries.

So this is a general bug in alpine's `getent`, or, worse, alpine's resolver.

**Comment by rade** [comment]
> So this is a general bug in alpine's `getent`, or, worse, alpine's resolver.

I think it's just [alpine's getent](https://github.com/alpinelinux/aports/blob/master/main/musl/getent.c), which only looks at the first entry returned by `gethostbyname()`.

**Comment by Multiply** [comment]
Sorry for not getting back to you @rade - Must've missed the notification.

Yes, the `getent` is only returning one record for me as well. I ended up using `nslookup` with `alpine` instead.
