### ISSUE TITLE
Merge proxy and router: refactorings & clean-ups

### ISSUE THREAD

**Issue by marccarre** [weaveworks/weave#2943]
Following up on #2936:

1. Move `mflag.BoolVar(&proxyConfig.*, [...])` close to router's arguments, as per [this](https://github.com/weaveworks/weave/pull/2936#discussion_r115518946) comment.
2. Refactor all proxy logic from `prog/weaver/main.go` in a single method, as per [this](https://github.com/weaveworks/weave/pull/2936#discussion_r115524284) comment.

**Comment by marccarre** [comment]
> Delete `PLUGIN_ARGS="--plugin"` and `ENABLE_PLUGIN=1` which are leftovers from [this commit](http://github.com/weaveworks/weave/commit/d2cbb2749e7d26adbaf325e9f2c43a841577b006). See also discussion starting [here](https://weaveworks.slack.com/archives/C0DNGPKLY/p1494345640315328).

is solved by #2951.

**Comment by bboreham** [comment]
> Factorise status HTTP endpoints. 

is #2960

**Comment by bboreham** [comment]
> As we start proxy.Serve(listeners) in a separate goroutine, it is not guaranteed that the proxy is ready when `wait_for_status` returns.

I now think this wasn't really a problem - the listening sockets are established so anyone who attempts to connect will just wait until `Accept()` is called by that separate goroutine.

#2946 makes `wait_for_status` wait longer, though still not for the `Accept()` goroutine.
